class Values {
  static const abilities = [
    'Air Lock',
    'Arena Trap',
    'Battle Armor',
    'Blaze',
    'Chlorophyll',
    'Clear Body',
    'Cloud Nine',
    'Color Change',
    'Compound Eyes',
    'Cute Charm',
    'Damp',
    'Drizzle',
    'Drought',
    'Early Bird',
    'Effect Spore',
    'Flame Body',
    'Flash Fire',
    'Forecast',
    'Guts',
    'Huge Power',
    'Hustle',
    'Hyper Cutter',
    'Illuminate',
    'Immunity',
    'Inner Focus',
    'Insomnia',
    'Intimidate',
    'Keen Eye',
    'Levitate',
    'Lightning Rod',
    'Limber',
    'Liquid Ooze',
    'Magma Armor',
    'Magnet Pull',
    'Marvel Scale',
    'Minus',
    'Natural Cure',
    'Oblivious',
    'Overgrow',
    'Own Tempo',
    'Pickup',
    'Plus',
    'Poison Point',
    'Pressure',
    'Pure Power',
    'Rain Dish',
    'Rock Head',
    'Rough Skin',
    'Run Away',
    'Sand Stream',
    'Sand Veil',
    'Serene Grace',
    'Shadow Tag',
    'Shed Skin',
    'Shell Armor',
    'Shield Dust',
    'Soundproof',
    'Speed Boost',
    'Static',
    'Stench',
    'Sticky Hold',
    'Sturdy',
    'Suction Cups',
    'Swarm',
    'Swift Swim',
    'Synchronize',
    'Thick Fat',
    'Torrent',
    'Trace',
    'Truant',
    'Vital Spirit',
    'Volt Absorb',
    'Water Absorb',
    'Water Veil',
    'White Smoke',
    'Wonder Guard',
  ];
  static const categories = [
    'Seed',
    'Lizard',
    'Flame',
    'Tiny Turtle',
    'Turtle',
    'Shellfish',
    'Worm',
    'Cocoon',
    'Butterfly',
    'Hairy Bug',
    'Poison Bee',
    'Tiny Bird',
    'Bird',
    'Mouse',
    'Beak',
    'Snake',
    'Cobra',
    'Poison Pin',
    'Drill ',
    'Fairy',
    'Fox',
    'Balloon',
    'Bat',
    'Weed',
    'Flower',
    'Mushroom',
    'Insect',
    'Mole',
    'Scratch Cat',
    'Classy Cat',
    'Duck',
    'Pig Monkey',
    'Puppy',
    'Legendary',
    'Tadpole',
    'Psi',
    'Superpower',
    'Flycatcher',
    'Jellyfish',
    'Rock',
    'Megaton',
    'Fire Horse',
    'Unique Horn',
    'Dopey',
    'Magnet',
    'Wild Duck',
    'Twin Bird',
    'Triple Bird',
    'Sea Lion',
    'Sludge',
    'Bivalve',
    'Gas',
    'Shadow',
    'Rock Snake',
    'Hypnosis',
    'River Crab',
    'Pincer',
    'Ball',
    'Egg',
    'Coconut',
    'Lonely',
    'Bone Keeper',
    'Kicking',
    'Punching',
    'Licking',
    'Poison Gas',
    'Spikes',
    'Vine',
    'Parent',
    'Dragon',
    'Goldfish',
    'Star Shape',
    'Mysterious',
    'Barrier',
    'Dancing',
    'Mantis',
    'Electric',
    'Spitfire',
    'Stag Beetle',
    'Wild Bull',
    'Fish',
    'Atrocious',
    'Transport',
    'Transform',
    'Evolution',
    'Bubble Jet',
    'Lightning',
    'Virtual',
    'Spiral ',
    'Fossil',
    'Sleeping',
    'Freeze',
    'Cruel',
    'Strong Legs',
    'Malevolent',
    'Genetic',
    'New Species',
  ];
  static const types = [
    'NORMAL',
    'FIRE',
    'WATER',
    'ELECTRIC',
    'GRASS',
    'ICE',
    'FIGHTING',
    'POISON',
    'GROUND',
    'FLYING',
    'PSYCHIC',
    'BUG',
    'ROCK',
    'GHOST',
    'DRAGON',
    'DARK',
    'STEEL',
    'FAIRY',
  ];
}
